#! /bin/bash

for i in $(seq 0 5); 
do
	for j in $(seq 0 $i);
	do
		echo -n " *"
	done
	echo " "
done

for (( i = 0; i < 5; i++ )); do
	for (( j = 0; j < $i; j++ )); do
		echo -n $i
	done
	echo ''
done

for (( i = 1; i <= 5; i++ )); do
	for (( j = 1; j <= $i; j++ )); do
		echo -n $j
	done
	echo ''
done

for (( i = 1; i <= 5; i++ )); do
	for (( j = 1; j <= $i; j++ )); do
		echo -n ' |'
	done
	echo -n '_ '
	echo ''
done

